services:
  fnos-automation:
    build: .
    image: fnos-server:latest
    container_name: fnos-server
    restart: unless-stopped
    shm_size: '1gb'
    ports:
      - "8836:8836"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./main.py:/app/main.py
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

